export interface TaxonomyEntry {
  slug: string;
  label: string;
  groupSlug: string;
  groupLabel: string;
  keywords: string[];
}

export const GROUPS: Record<string, string> = {
  "website-hosting": "Website & Hosting",
  ecommerce: "E-commerce",
  accounting: "Accounting & Finance",
  "finance-trading": "Trading & Investing",
  payments: "Payments & Billing",
  productivity: "Productivity & Office",
  "project-management": "Project Management",
  design: "Design & Creative",
  "marketing-crm": "Marketing & CRM",
  "forms-surveys": "Forms & Surveys",
  "customer-support": "Customer Support",
  communication: "Communication",
  "ai-tools": "AI Tools",
  "data-bi": "Data & Analytics",
  "social-media": "Social Media",
  "online-learning": "Online Learning",
  "developer-tools": "Developer Tools",
  "seo-marketing": "SEO & Marketing",
  automation: "Automation & Integrations",
  other: "Other Topics",
};

// Ordered roughly by video volume (highest first). Order only matters as a
// tiebreaker when a title mentions multiple tools at the same position.
export const TAXONOMY: TaxonomyEntry[] = [
  { slug: "canva", label: "Canva", groupSlug: "design", groupLabel: GROUPS.design, keywords: ["canva"] },
  { slug: "quickbooks", label: "QuickBooks", groupSlug: "accounting", groupLabel: GROUPS.accounting, keywords: ["quickbooks online", "quickbooks"] },
  { slug: "google-docs", label: "Google Docs", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["google docs"] },
  { slug: "squarespace", label: "Squarespace", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["squarespace"] },
  { slug: "jira", label: "Jira", groupSlug: "project-management", groupLabel: GROUPS["project-management"], keywords: ["jira"] },
  { slug: "gohighlevel", label: "GoHighLevel", groupSlug: "marketing-crm", groupLabel: GROUPS["marketing-crm"], keywords: ["gohighlevel", "go highlevel", "high level crm"] },
  { slug: "power-bi", label: "Power BI", groupSlug: "data-bi", groupLabel: GROUPS["data-bi"], keywords: ["power bi", "powerbi"] },
  { slug: "turbotax", label: "TurboTax", groupSlug: "accounting", groupLabel: GROUPS.accounting, keywords: ["turbotax"] },
  { slug: "google-sheets", label: "Google Sheets", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["google sheets", "google sheet"] },
  { slug: "shopify", label: "Shopify", groupSlug: "ecommerce", groupLabel: GROUPS.ecommerce, keywords: ["shopify"] },
  { slug: "claude-ai", label: "Claude AI", groupSlug: "ai-tools", groupLabel: GROUPS["ai-tools"], keywords: ["claude ai", "claude"] },
  { slug: "confluence", label: "Confluence", groupSlug: "project-management", groupLabel: GROUPS["project-management"], keywords: ["confluence"] },
  { slug: "tradingview", label: "TradingView", groupSlug: "finance-trading", groupLabel: GROUPS["finance-trading"], keywords: ["tradingview", "trading view"] },
  { slug: "slack", label: "Slack", groupSlug: "communication", groupLabel: GROUPS.communication, keywords: ["slack"] },
  { slug: "outlook", label: "Outlook", groupSlug: "communication", groupLabel: GROUPS.communication, keywords: ["microsoft outlook", "outlook"] },
  { slug: "zapier", label: "Zapier", groupSlug: "automation", groupLabel: GROUPS.automation, keywords: ["zapier"] },
  { slug: "google-workspace", label: "Google Workspace", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["google workspace"] },
  { slug: "brevo", label: "Brevo", groupSlug: "marketing-crm", groupLabel: GROUPS["marketing-crm"], keywords: ["brevo"] },
  { slug: "paypal", label: "PayPal", groupSlug: "payments", groupLabel: GROUPS.payments, keywords: ["paypal"] },
  { slug: "trello", label: "Trello", groupSlug: "project-management", groupLabel: GROUPS["project-management"], keywords: ["trello"] },
  { slug: "webflow", label: "Webflow", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["webflow"] },
  { slug: "clickup", label: "ClickUp", groupSlug: "project-management", groupLabel: GROUPS["project-management"], keywords: ["clickup"] },
  { slug: "gumroad", label: "Gumroad", groupSlug: "ecommerce", groupLabel: GROUPS.ecommerce, keywords: ["gumroad"] },
  { slug: "cloudflare", label: "Cloudflare", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["cloudflare"] },
  { slug: "freshdesk", label: "Freshdesk", groupSlug: "customer-support", groupLabel: GROUPS["customer-support"], keywords: ["freshdesk"] },
  { slug: "hubspot", label: "HubSpot", groupSlug: "marketing-crm", groupLabel: GROUPS["marketing-crm"], keywords: ["hubspot"] },
  { slug: "excel", label: "Microsoft Excel", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["microsoft excel", "excel"] },
  { slug: "zendesk", label: "Zendesk", groupSlug: "customer-support", groupLabel: GROUPS["customer-support"], keywords: ["zendesk"] },
  { slug: "typeform", label: "Typeform", groupSlug: "forms-surveys", groupLabel: GROUPS["forms-surveys"], keywords: ["typeform"] },
  { slug: "microsoft-loop", label: "Microsoft Loop", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["microsoft loop"] },
  { slug: "monday", label: "Monday.com", groupSlug: "project-management", groupLabel: GROUPS["project-management"], keywords: ["monday.com", "monday crm"] },
  { slug: "airtable", label: "Airtable", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["airtable"] },
  { slug: "hostinger", label: "Hostinger", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["hostinger"] },
  { slug: "smartsheet", label: "Smartsheet", groupSlug: "project-management", groupLabel: GROUPS["project-management"], keywords: ["smartsheet"] },
  { slug: "microsoft-teams", label: "Microsoft Teams", groupSlug: "communication", groupLabel: GROUPS.communication, keywords: ["microsoft teams"] },
  { slug: "wix", label: "Wix", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["wix"] },
  { slug: "asana", label: "Asana", groupSlug: "project-management", groupLabel: GROUPS["project-management"], keywords: ["asana"] },
  { slug: "microsoft-forms", label: "Microsoft Forms", groupSlug: "forms-surveys", groupLabel: GROUPS["forms-surveys"], keywords: ["microsoft forms"] },
  { slug: "ebay", label: "eBay", groupSlug: "ecommerce", groupLabel: GROUPS.ecommerce, keywords: ["ebay"] },
  { slug: "stripe", label: "Stripe", groupSlug: "payments", groupLabel: GROUPS.payments, keywords: ["stripe"] },
  { slug: "namecheap", label: "Namecheap", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["namecheap"] },
  { slug: "gmail", label: "Gmail", groupSlug: "communication", groupLabel: GROUPS.communication, keywords: ["gmail"] },
  { slug: "power-automate", label: "Power Automate", groupSlug: "automation", groupLabel: GROUPS.automation, keywords: ["power automate"] },
  { slug: "godaddy", label: "GoDaddy", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["godaddy"] },
  { slug: "jotform", label: "Jotform", groupSlug: "forms-surveys", groupLabel: GROUPS["forms-surveys"], keywords: ["jotform"] },
  { slug: "instagram", label: "Instagram", groupSlug: "social-media", groupLabel: GROUPS["social-media"], keywords: ["instagram"] },
  { slug: "chatgpt", label: "ChatGPT", groupSlug: "ai-tools", groupLabel: GROUPS["ai-tools"], keywords: ["chatgpt", "chat gpt"] },
  { slug: "gemini", label: "Gemini", groupSlug: "ai-tools", groupLabel: GROUPS["ai-tools"], keywords: ["gemini"] },
  { slug: "coursera", label: "Coursera", groupSlug: "online-learning", groupLabel: GROUPS["online-learning"], keywords: ["coursera"] },
  { slug: "notion", label: "Notion", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["notion"] },
  { slug: "google-drive", label: "Google Drive", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["google drive"] },
  { slug: "elementor", label: "Elementor", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["elementor"] },
  { slug: "wordpress", label: "WordPress", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["wordpress"] },
  { slug: "github", label: "GitHub", groupSlug: "developer-tools", groupLabel: GROUPS["developer-tools"], keywords: ["github"] },
  { slug: "udemy", label: "Udemy", groupSlug: "online-learning", groupLabel: GROUPS["online-learning"], keywords: ["udemy"] },
  { slug: "sharepoint", label: "SharePoint", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["sharepoint"] },
  { slug: "figma", label: "Figma", groupSlug: "design", groupLabel: GROUPS.design, keywords: ["figma"] },
  { slug: "google-slides", label: "Google Slides", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["google slides"] },
  { slug: "zoom", label: "Zoom", groupSlug: "communication", groupLabel: GROUPS.communication, keywords: ["zoom"] },
  { slug: "semrush", label: "Semrush", groupSlug: "seo-marketing", groupLabel: GROUPS["seo-marketing"], keywords: ["semrush"] },
  { slug: "binance", label: "Binance", groupSlug: "finance-trading", groupLabel: GROUPS["finance-trading"], keywords: ["binance"] },
  { slug: "grammarly", label: "Grammarly", groupSlug: "productivity", groupLabel: GROUPS.productivity, keywords: ["grammarly"] },
  { slug: "facebook", label: "Facebook", groupSlug: "social-media", groupLabel: GROUPS["social-media"], keywords: ["facebook"] },
  { slug: "etsy", label: "Etsy", groupSlug: "ecommerce", groupLabel: GROUPS.ecommerce, keywords: ["etsy"] },
  { slug: "google-sites", label: "Google Sites", groupSlug: "website-hosting", groupLabel: GROUPS["website-hosting"], keywords: ["google sites"] },
  { slug: "whatsapp", label: "WhatsApp", groupSlug: "social-media", groupLabel: GROUPS["social-media"], keywords: ["whatsapp"] },
  { slug: "google-chat", label: "Google Chat", groupSlug: "communication", groupLabel: GROUPS.communication, keywords: ["google chat"] },
  { slug: "n8n", label: "n8n", groupSlug: "automation", groupLabel: GROUPS.automation, keywords: ["n8n"] },
  { slug: "chrome", label: "Google Chrome", groupSlug: "developer-tools", groupLabel: GROUPS["developer-tools"], keywords: ["google chrome", "chrome browser", "chrome"] },
];
